---
- name: Create New Resource Group
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Create new resource group
      ansible.builtin.command: ls
      args:
        chdir: '~/'
      register: output_ip_address
    - name: Dump public IP for VM which will be created
      debug:
        msg: "The public IP is {{ output_ip_address }}"
